openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /users/{getUserId}:
    get:
      tags:
        - users
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      operationId: getUsers
      parameters:
        - $ref: '#/components/parameters/getUserId'
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNameListTO'

components:
  parameters:
    getUserId:
      name: getUserId
      in: path
      description: id with wich to get users
      required: true
      schema:
        type: integer
        format: int64

  schemas:
    UserNameListTO:
      type: object
      required:
        - list
      properties:
        list:
          type: array
          description: list of User Names
          items:
            $ref: '#/components/schemas/UserNameTO'

    UserNameTO:
      type: object
      required:
        - first
        - last
      properties:
        first:
          type: string
        last:
          type: string
        middle:
          type: string

